{
 "title": "Orders",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Order Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "demo_data",
     "rawSql": "SELECT COUNT(status) as 'In Process' FROM demo_data.orders WHERE status = 'In Process' "
    },
    {
     "dataset": "demo_data",
     "rawSql": "SELECT COUNT(status) as 'On Hold' FROM demo_data.orders WHERE status = 'On Hold' GROUP BY status"
    },
    {
     "dataset": "demo_data",
     "rawSql": "SELECT COUNT(status) as 'Shipped' FROM demo_data.orders WHERE status = 'Shipped' GROUP BY status LIMIT 50 "
    },
    {
     "dataset": "demo_data",
     "rawSql": "SELECT\n  COUNT(status) as Cancelled\nFROM\n  demo_data.orders\nWHERE\n  status = 'Cancelled'\nGROUP BY\n  status\n"
    }
   ]
  },
  {
   "title": "Pending Orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "demo_data",
     "rawSql": "select\n    o.orderNumber as 'Order Number',\n    c.customerName as 'Customer',\n    o.requiredDate as 'Delivery Date',\n    (select sum(quantityOrdered * priceEach) from orderdetails od where od.orderNumber = o.orderNumber) as 'Order Total'\nfrom\n    orders o\n    inner join\n    customers c on o.customerNumber = c.customerNumber\nwhere\n    status = 'In Process'\norder by\n    o.requiredDate asc"
    }
   ]
  },
  {
   "title": "Orders - 2004",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "demo_data",
     "rawSql": "SELECT\n    date_format(orderDate, '%M') as Month,\n    COUNT(orderNumber) as Orders\nFROM\n    demo_data.orders\nWHERE\n    orderDate BETWEEN '2004-01-01'\n        AND '2004-12-31'\nGROUP BY\n    date_format(orderDate, '%M')\n"
    }
   ]
  }
 ]
}